services:

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=172.17.51.94
      - DB_USER=982807
      - DB_PASSWORD=982807
      - DB_NAME=982807
      - DB_PORT=3307
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    user: "${UID:-1}:${GID:-1}"
volumes:
  data: